### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RichardLitt** [kristopherjohnson/MenubarCountdown#1]
I couldn't head to http://capablehands.net/menubarcountdown. Thanks.

**Comment by kristopherjohnson** [comment]
There is a new beta build available: https://github.com/kristopherjohnson/MenubarCountdown/releases/tag/2.0b1

I will update links in the documentation and application when I find a new home for it.

**Comment by kristopherjohnson** [comment]
The 2.0 beta 2 build changes the link to point to the GitHub page. 

https://github.com/kristopherjohnson/MenubarCountdown/releases/tag/2.0b2
