### ISSUE TITLE
32-bit app compatibility with macOS High Sierra 10.13.4 and later

### ISSUE THREAD

**Issue by fharper** [kristopherjohnson/MenubarCountdown#2]
When you start the app in macOS Mojave, you get [this warning](https://support.apple.com/en-ca/HT208436).

**Comment by kristopherjohnson** [comment]
There is a new beta build that is 64-bit.

https://github.com/kristopherjohnson/MenubarCountdown/releases/tag/2.0b1

Please test that build, and if the the issue still occurs, please open another issue.
