### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by themacmarketer** [kristopherjohnson/MenubarCountdown#21]
Does anyone know if there is any way to control the volume of the spoken announcement?
My meeting attendees sometimes get a shock when the timer ends and the loud voice sounds.
Thanks !

**Comment by kristopherjohnson** [comment]
I don't know of a way to do it.

You might try this advice for changing the Siri voice output volume, but I don't know whether this affects all speech output or only Siri: https://support.apple.com/en-us/HT209573

**Comment by kristopherjohnson** [comment]
If you put `[[volm 0.5]]` at the beginning of the announcement, it will be spoken at half volume.

Documentation for other embedded speech commands is available here: https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/SpeechSynthesisProgrammingGuide/FineTuning/FineTuning.html

**Comment by themacmarketer** [comment]
Thank you!

I used this syntax and it seems to work fine:

set announcement text to "[[volm 0.10]] \"" & "My announcement."
