### ISSUE TITLE
Countdown not showing in second monitor menu bar

### ISSUE THREAD

**Issue by gsportelli** [kristopherjohnson/MenubarCountdown#29]
When I have a second monitor attached, the countdown is shown only in the primary one and only when it is active (i.e., the active window is in the first monitor). If the active monitor is the secondary, the countdown is not shown on either monitor.
I would expect the countdown to show on both, or even better, to always show on the active monitor.

**Comment by kristopherjohnson** [comment]
I have three monitors myself, and the countdown shows in all three menu bars at the same time. If I enable showing seconds, I see the timer counting down on the inactive monitors in addition to the active one.

Are you running any special menu-bar management software (e.g. Bartender)?

**Comment by gsportelli** [comment]
Ohh sorry, my bad. I'm using two Macs with universal control as well as Bartender. It's so seamless that sometimes I forget they are two separate devices.
When I move out of the screen of my primary Mac, the menubar dims, and all the menubar items disappear. However, it's not a problem of the app.

Thanks anyway for your reply and for the great app!
