### ISSUE TITLE
"Start" hotkey

### ISSUE THREAD

**Issue by akapitoha** [kristopherjohnson/MenubarCountdown#7]
Hi,

I've tried lots of timers for mac os, but guess MenubarCountdown is the best one (for me).
I wish there we 2 options:
1. hotkey to quickly start a timer via keyboard
2. display just icon in menu bar instead of actual remaining time

thank you

**Comment by kristopherjohnson** [comment]
Key shortcuts can be set in System Preferences > Keyboard > Shortcuts > Services > General:

<img width="780" alt="MenubarCountdownShortcuts" src="https://user-images.githubusercontent.com/22244/78088491-519ec300-7392-11ea-9ac1-6577fe2fa9d9.png">

I'll consider a just-display-icon option.
